services:
  database:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: admin  # Passwort für den root-User
      MYSQL_USER: user  # Benutzername für die Datenbank
      MYSQL_PASSWORD: oaiszdiufiansdfo  # Passwort für den Benutzer
      MYSQL_DATABASE: summergames  # Name der initialen Datenbank
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"

  frontend:
    build:
      context: ./frontend
    ports:
      - "1313:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    depends_on:
      - database

volumes:
  mysql-data:
    driver: local