services:
  database:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: admin  # Passwort für den root-User
      MYSQL_USER: user  # Benutzername für die Datenbank
      MYSQL_PASSWORD: oaiszdiufiansdfo  # Passwort für den Benutzer
      MYSQL_DATABASE: summergames  # Name der initialen Datenbank
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    ports:
      - "1313:80"
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    build:
      context: ./backend
    depends_on:
      - database
    restart: unless-stopped

  adminer:
    image: adminer
    ports:
      - "3307:8080"
    restart: unless-stopped

volumes:
  mysql-data:
    driver: local